### ISSUE TITLE
RSS tables not being made in default.db

### ISSUE THREAD

**Issue by rinzes** [f4bio/sopel-rss#6]
no rss tables in default.db I have sqlite3 installed

**Comment by RebelCodeBase** [comment]
Could you please be more verbose?  What are you doing? How do you detect that error? Is there an error message?

**Comment by rinzes** [comment]
I start sopel with "sopel -d which made a default.db file
then in the #channel I do  .rssadd #globalnews CNBC http://www.cnbc.com/id/100003114/device/rss/rss.html which returns

$ [sopel-rss] [ERROR] unable to add feed "http://www.cnbc.com/id/100003114/device/rss/rss.html"

I then looked in the default.db with sqlitebrowser and see no rss tables made

**Comment by RebelCodeBase** [comment]
It turns out the the last problem was related. So here is the story:
sopel uses python3! 
python3 needs 
`from urllib.request import urlopen`
So I reinserted the line and added the feed to my test bot. It works:
`sopel-dev: [INFO] added to channel "#sopel-dev" rss feed "CNBC" with url "http://www.cnbc.com/id/100003114/device/rss/rss.html"`
It creates a new table and posts the latest news CNBC news.

Why didn't I notice that the line was vital when I removed it? Because I have just started to write tests...

**Comment by rinzes** [comment]
and mine was I had to use sopel with python 3 which I solved using virtualenv. All is now well "for now" :)

**Comment by RebelCodeBase** [comment]
Very well. I will now add tests to the rss module. Then I'd like to add an option which rss fields should be cached (i.e. when is a rss item considered "new"?) and an option to control which fields should be printed by the bot. Afterwards, I'll make a first release. :-)
